name: ci-windows-arm

on:
  push:
    branches: [main]
    tags: ["**"]
  pull_request:
    branches: [main]
    types: [labeled, opened, synchronize, reopened]

permissions: write-all

jobs:
  build-windows-arm:
    name: release aarch64-pc-windows-msvc
    runs-on: windows-11-arm
    timeout-minutes: 180

    env:
      V8_FROM_SOURCE: true
      CARGO_VARIANT_FLAG: --release
      CARGO_FEATURE_FLAGS: ""
      LIB_NAME: rusty_v8
      LIB_EXT: lib
      FEATURES_SUFFIX: ""
      RUSTFLAGS: -D warnings

    steps:
      - name: Configure git
        run: git config --global core.symlinks true

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
          submodules: recursive

      - name: Install rust
        uses: dsherret/rust-toolchain-file@v1

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install nextest
        run: cargo binstall cargo-nextest --secure

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.x
     
      - name: Write git_submodule_status.txt
        run: git submodule status --recursive > git_submodule_status.txt

      - name: Cache
        uses: actions/cache@v4
        with:
          # Note: rusty_v8 targets always get get rebuilt, and their outputs
          # ('librusty_v8.rlib', the whole 'gn_out' directory, etc.) can be
          # quite big, so we cache only those subdirectories of
          # target/{debug|release} that contain the build output for crates that
          # come from the registry. By additionally saving the sccache cache
          # directory it's still possible to build v8 fast.
          path: |-
            target/sccache
            target/*/.*
            target/*/build
            target/*/deps
          key: cargo1-aarch64-pc-windows-msvc-${{ hashFiles('Cargo.lock', 'build.rs', 'git_submodule_status.txt') }}
          restore-keys: cargo1-aarch64-pc-windows-msvc-

      - name: Install and start sccache
        shell: pwsh
        env:
          SCCACHE_DIR: ${{ github.workspace }}/target/sccache
          SCCACHE_CACHE_SIZE: 256M
          SCCACHE_IDLE_TIMEOUT: 0
        run: |
          $version = "v0.8.2"
          $platform =
            @{ "x86_64-apple-darwin"       = "x86_64-apple-darwin"
               "aarch64-apple-darwin"      = "aarch64-apple-darwin"
               "x86_64-unknown-linux-gnu"  = "x86_64-unknown-linux-musl"
               "aarch64-unknown-linux-gnu" = "aarch64-unknown-linux-musl"
               "x86_64-pc-windows-msvc"    = "x86_64-pc-windows-msvc"
               "aarch64-pc-windows-msvc"   = "aarch64-pc-windows-msvc"
             }['aarch64-pc-windows-msvc']
          $basename = "sccache-$version-$platform"
          $url = "https://github.com/mozilla/sccache/releases/download/$version/$basename.tar.gz"
          cd ~
          curl -LO $url
          tar -xzvf "$basename.tar.gz"
          . $basename/sccache --start-server
          echo "$(pwd)/$basename" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: check rust code formatting
        run: cargo fmt --check

      - name: Test
        env:
          SCCACHE_IDLE_TIMEOUT: 0
        run: cargo nextest run -v --cargo-verbose --cargo-verbose --all-targets --locked --target aarch64-pc-windows-msvc ${{ env.CARGO_VARIANT_FLAG }} ${{ env.CARGO_FEATURE_FLAGS }}

      - name: Clippy
        run: cargo clippy --all-targets --locked --target aarch64-pc-windows-msvc ${{ env.CARGO_VARIANT_FLAG }} ${{ env.CARGO_FEATURE_FLAGS }} -- -D clippy::all
